### ISSUE TITLE
Handle multi-arch builds in destructive mode

### ISSUE THREAD

**Issue by mr-cal** [canonical/snapcraft#4356]
### What needs to get done

When running in destructive mode, snapcraft should do one of the following:

This issue is referenced in the documentation and should be updated when completed.  (both [readthedocs](https://canonical-snapcraft.readthedocs-hosted.com/en/latest/explanation/index.html) and snapcraft.io/docs)

#### option 1
organize craft-parts directories by architecture:
```
my-snap-project
├─ amd64
│  ├── parts
│  ├── prime
│  └── stage
└─ arm64
   ├── parts
   ├── prime
   └── stage
```

#### option 2
store the architecture in the craft-parts state file and clean between builds of different architectures

### Why it needs to get done

Consider the `snapcraft.yaml` snippet:
```yaml
base: core22
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: amd64
    build-for: arm64
```

When `snapcraft --destructive-mode` is executed, it will build for `amd64` and then for `arm64`.  
On the build for `arm64`, all steps will be skipped.  There is no isolation between the builds.

This is not a problem for core20 snaps.
