### ISSUE TITLE
Support component hooks

### ISSUE THREAD

**Issue by mr-cal** [canonical/snapcraft#4570]
### `snapcraft.yaml` syntax

Support the following syntax:
```yaml
components:
  <component-name>:
    hooks:
      <hook-name>:
        plugs:
          - <plug-name>
        <all-currently-valid-hooks>
```

Supported hooks are:
- install
- pre-refresh
- post-refresh
- remove

### `meta/snap.yaml` syntax

The `meta/snap.yaml` needs to list all component metadata, including the component hooks.  Currently, this is not happening.

### Why it needs to get done

To support component hooks
