### ISSUE TITLE
snapcraft 8.2.0.post3+gitc9ab9d1d from edge doesn't support refresh-mode: ignore-running

### ISSUE THREAD

**Issue by kenvandine** [canonical/snapcraft#4747]
### Bug Description

The documentation shows ignore-running as a valid option for refresh-mode

https://snapcraft.io/docs/snapcraft-app-and-service-metadata

However when building snapcraft reports:
```
unexpected value; permitted: 'endure', 'restart'
```

### To Reproduce

Add "refresh-mode: ignore-running" to the app 

### Environment

snapcraft from edge with lxd

### snapcraft.yaml

```shell
+    refresh-mode: ignore-running
```

### Relevant log output

```shell
unexpected value; permitted: 'endure', 'restart'
```

**Comment by mr-cal** [comment]
Thanks for the report!  I can reproduce this in snapcraft `7.x/stable` and `8.x/stable` with `core20` and `core22`.  

@kenvandine, was this previously working for you?

It appears that it should have never worked ([source](https://github.com/canonical/snapcraft/blob/c9ab9d1dbc69ddca6a2cf0ddb2b583838a2489b8/snapcraft/models/project.py#L375) and [source](https://github.com/canonical/snapcraft/blob/c9ab9d1dbc69ddca6a2cf0ddb2b583838a2489b8/schema/snapcraft.json#L773)).  Here's my core22 reproducer:
```yaml
name: test
version: '0.1'
summary: test
description: test

grade: devel
confinement: devmode

base: core22

parts:
  my-part:
    plugin: nil
    override-build: |
      touch $CRAFT_PART_INSTALL/hello
      chmod +x $CRAFT_PART_INSTALL/hello
      craftctl default

apps:
  my-app:
    command: hello
    refresh-mode: ignore-running
```
