### ISSUE TITLE
snapcraft 7 ignores icon path in snapcraft.yaml

### ISSUE THREAD

**Issue by mapero** [canonical/snapcraft#4936]
### Bug Description

I have minimal example of a snapcraft.yaml
```
name: icon-snap
base: core22
version: '0.1'
summary: icon snap
icon: icon/icon.png
description: minimal
grade: stable
confinement: strict
parts:
  my-part:
    plugin: nil
```

It seems like the icon is not copied when there is no "apps" section defined in the snapcraft.yaml in snapcraft 7. With snapcraft 6 or legacy the icon is copied into the snap:

With snapcraft 6 / legacy
```
prime/
└── meta
    ├── gui
    │   └── icon.png
    └── snap.yaml

2 directories, 2 files
```

With snapcraft 7
```
prime/
└── meta
    ├── gui
    └── snap.yaml

2 directories, 1 file
```

### To Reproduce

Build the following snap with snapcraft 7:

```
name: icon-snap
base: core22
version: '0.1'
summary: icon snap
icon: icon/icon.png
description: minimal
grade: stable
confinement: strict
parts:
  my-part:
    plugin: nil
```

### Environment

Ubuntu 22.04 LTS

### snapcraft.yaml

```shell
name: icon-snap
base: core22
version: '0.1'
summary: icon snap
icon: icon/icon.png
description: minimal
grade: stable
confinement: strict
parts:
  my-part:
    plugin: nil
```

### Relevant log output

```shell
NA
```
