### ISSUE TITLE
The snap CLI incorrectly indicates that installation is possible from a closed channel.

### ISSUE THREAD

**Issue by bschimke95** [canonical/snapcraft#5175]
### Bug Description

Hi everyone,

We maintain the `k8s` snap and provide the following channels for each Kubernetes release:

```
1.XX  
1.XX-classic  
1.XX-moonray  
```

We now had to close the 1.XX channels.

However, the snap CLI is now suggesting that the installation can proceed from higher-risk channels when attempting to install from 1.31/candidate, even though the channel is closed:
```
root@c2:~# sudo snap install k8s --channel=1.31/candidate  
error: snap "k8s" is not available on 1.31/candidate but is available to install on the following  
       channels:  

       1.31/beta  snap install --channel=1.31/beta k8s  
       1.31/edge  snap install --channel=1.31/edge k8s  

       Get more information with 'snap info k8s'. 
``` 
Further attempts to install from 1.31/beta and 1.31/edge produce similar errors, with the CLI falling back to listing other tracks:

```
root@c2:~# sudo snap install k8s --channel=1.31/edge  
error: snap "k8s" is not available on 1.31/edge but is available to install on the following tracks:  

       latest/candidate        snap install --candidate k8s  
       ...  
       1.31-classic/candidate  snap install --channel=1.31-classic/candidate k8s  
       1.31-classic/beta       snap install --channel=1.31-classic/beta k8s  
       1.31-classic/edge       snap install --channel=1.31-classic/edge k8s  
       1.31-moonray/candidate  snap install --channel=1.31-moonray/candidate k8s  
       ...  

       Please be mindful that different tracks may include different features. Get more information  
       with 'snap info k8s'.  
```
Let us know if this is intended behavior or have suggestions for handling closed channels in this scenario.

Thanks!

### To Reproduce

Try to install from any risk level in 1.31
```
sudo snap install k8s --channel 1.31/candidate
``` 

### Environment

tested on LXD 22.04 but this also happens in other environments.  

### snapcraft.yaml

```yaml
name: k8s
adopt-info: kubernetes-version
summary: Canonical Kubernetes, a CNCF-conformant K8s distribution by Canonical
description: |-
  Canonical Kubernetes is an opinionated and CNCF conformant Kubernetes delivered by snaps.
  Enjoy the simplified, almost zero, operations and enhanced security posture
  on any infrastructure
license: GPL-3.0
grade: stable
confinement: classic
base: core20
environment:
  REAL_PATH: $PATH
  REAL_LD_LIBRARY_PATH: $LD_LIBRARY_PATH
  SNAPCRAFT_ARCH_TRIPLET: $SNAPCRAFT_ARCH_TRIPLET

architectures:
  - build-on: [amd64]
  - build-on: [arm64]

parts:
  build-deps:
    plugin: nil
    build-snaps:
      - go/1.22/stable
    build-packages:
      - autoconf
      - automake
      - autopoint
      - autotools-dev
      - bison
      - btrfs-progs
      - libbtrfs-dev
      - build-essential
      - curl
      - flex
      - git
      - libjansson-dev
      - liblz4-dev
      - libnetfilter-conntrack-dev
      - libnetfilter-conntrack3
      - libnfnetlink-dev
      - libseccomp-dev
      - libtool
      - pkg-config
      - rsync
      - tcl

  dqlite:
    after: [build-deps]
    plugin: nil
    source: src/k8s/hack
    override-prime: ""
    override-build: |
      DQLITE_STAGING_DIR="${SNAPCRAFT_STAGE}/static-dqlite-deps"
      if [ -d "${DQLITE_STAGING_DIR}" ]; then
        rm -rf "${DQLITE_STAGING_DIR}"
      fi
      mkdir "${DQLITE_STAGING_DIR}"
      cp -rv * "${DQLITE_STAGING_DIR}"

      # Build dqlite libraries on the staging area
      "${DQLITE_STAGING_DIR}/static-dqlite.sh"

  k8s-dqlite:
    after: [dqlite]
    plugin: nil
    source: build-scripts/components/k8s-dqlite
    override-build: $SNAPCRAFT_PROJECT_DIR/build-scripts/build-component.sh k8s-dqlite

  k8s-binaries:
    after: [dqlite]
    source: src/k8s
    plugin: nil
    override-build: |
      INSTALL="${SNAPCRAFT_PART_INSTALL}"

      export DQLITE_BUILD_SCRIPTS_DIR="${SNAPCRAFT_STAGE}/static-dqlite-deps"
      make static -j

      mkdir -p "${INSTALL}/bin"
      for binary in k8s k8sd k8s-apiserver-proxy; do
        cp -P "bin/static/${binary}" "${INSTALL}/bin/${binary}"
      done
      ./bin/static/k8s list-images > "${INSTALL}/images.txt"

  cni:
    after: [build-deps]
    plugin: nil
    source: build-scripts/components/cni
    override-build: $SNAPCRAFT_PROJECT_DIR/build-scripts/build-component.sh cni

  kubernetes:
    after: [build-deps]
    plugin: nil
    source: build-scripts
    override-build: $SNAPCRAFT_PROJECT_DIR/build-scripts/build-component.sh kubernetes

  kubernetes-version:
    plugin: nil
    source: build-scripts/components/kubernetes
    override-build: snapcraftctl set-version "$(cat ./version)"

  helm:
    after: [build-deps]
    build-attributes: [no-patchelf]
    plugin: nil
    source: build-scripts/components/helm
    override-build: $SNAPCRAFT_PROJECT_DIR/build-scripts/build-component.sh helm

  libmnl:
    after: [build-deps]
    plugin: autotools
    source: https://www.netfilter.org/pub/libmnl/libmnl-1.0.4.tar.bz2
    prime:
      - -usr/local/include

  libnftnl:
    after: [libmnl]
    plugin: autotools
    source: https://www.netfilter.org/projects/libnftnl/files/libnftnl-1.1.8.tar.bz2
    build-environment:
      - LIBMNL_LIBS: $SNAPCRAFT_STAGE/usr/lib
    prime:
      - -usr/local/include

  iptables:
    after: [libnftnl]
    source: https://www.netfilter.org/projects/iptables/files/iptables-1.8.6.tar.bz2
    plugin: autotools
    build-environment:
      - LIBMNL_LIBS: $SNAPCRAFT_STAGE/usr/lib
      - LIBNFTNL_LIBS: $SNAPCRAFT_STAGE/usr/lib
    autotools-configure-parameters:
      - "--prefix=/usr"
      - "--exec-prefix=/"
      - "--disable-shared"
      - "--enable-static"
    stage:
      - -usr
      - -lib/pkgconfig
      - -bin/iptables-xml

  containerd:
    after: [runc]
    plugin: nil
    build-attributes: [no-patchelf]
    source: build-scripts/components/containerd
    override-build: $SNAPCRAFT_PROJECT_DIR/build-scripts/build-component.sh containerd

  runc:
    after: [iptables, build-deps]
    plugin: nil
    build-attributes: [no-patchelf]
    source: build-scripts/components/runc
    override-build: $SNAPCRAFT_PROJECT_DIR/build-scripts/build-component.sh runc

  bash-utils:
    plugin: nil
    stage-packages:
      - conntrack
      - coreutils
      - diffutils
      - ethtool
      - hostname
      - iproute2
      - ipset
      - kmod
      - libatm1
      - libnss-resolve
      - libnss-myhostname
      - libnss-mymachines
      - members
      - nano
      - net-tools
      - openssl
      - procps
      - tar
      - util-linux
    stage:
      - -etc/bash_completion.d
      - -etc/cron.d
      - -etc/depmod.d
      - -etc/ldap
      - -etc/logrotate.d
      - -etc/init.d
      - -etc/perl
      - -etc/rsyslog.d
      - -etc/sudoers.d
      - -lib/systemd
      - -usr/bin/perl*
      - -usr/include
      - -usr/lib/*/*perl*
      - -usr/share

  k8s:
    plugin: nil
    source: k8s
    override-build: |
      rm $SNAPCRAFT_PART_INSTALL/k8s -rf
      cp --archive --link --no-dereference . $SNAPCRAFT_PART_INSTALL/k8s

  bom:
    after:
      - cni
      - containerd
      - helm
      - k8s-dqlite
      - kubernetes
      - runc
    plugin: nil
    source: .
    build-packages:
      - python3-yaml
    override-build: |
      ./build-scripts/generate-bom.py > "${SNAPCRAFT_PART_INSTALL}/bom.json"

apps:
  k8s:
    command: k8s/wrappers/commands/k8s
  containerd:
    command: k8s/wrappers/services/containerd
    daemon: notify
    install-mode: disable
    # when stopped send only sigterm
    # https://forum.snapcraft.io/t/process-lifecycle-on-snap-refresh/140/37
    stop-mode: sigterm
    restart-condition: always
    start-timeout: 5m
    before: [kubelet]
  k8s-dqlite:
    command: k8s/wrappers/services/k8s-dqlite
    install-mode: disable
    daemon: simple
    before: [kube-apiserver]
  k8sd:
    command: k8s/wrappers/services/k8sd
    install-mode: enable
    daemon: simple
  kubelet:
    install-mode: disable
    command: k8s/wrappers/services/kubelet
    daemon: simple
    after: [containerd]
  kube-apiserver:
    install-mode: disable
    command: k8s/wrappers/services/kube-apiserver
    daemon: simple
    before: [kubelet, kube-controller-manager, kube-proxy, kube-scheduler]
    stop-timeout: 5s
  kube-controller-manager:
    install-mode: disable
    command: k8s/wrappers/services/kube-controller-manager
    daemon: simple
    after: [kube-apiserver]
  kube-proxy:
    install-mode: disable
    command: k8s/wrappers/services/kube-proxy
    daemon: simple
    after: [kube-apiserver]
  kube-scheduler:
    install-mode: disable
    command: k8s/wrappers/services/kube-scheduler
    daemon: simple
    after: [kube-apiserver]
  k8s-apiserver-proxy:
    install-mode: disable
    command: k8s/wrappers/services/k8s-apiserver-proxy
    daemon: simple
    before: [kubelet, kube-proxy]
```

### Relevant log output

```shell
-
```
