### ISSUE TITLE
Snapcraft conflates standard PyPI packages with local plugins

### ISSUE THREAD

**Issue by bepri** [canonical/snapcraft#5217]
### Bug Description

When upgrading dependencies, it was discovered that building Snapcraft with `cryptography==44.0.0` introduced a new `rust` module to the `site-packages` directory. Doing this caused Snapcraft to attempt to use the contents of this module instead of the proper `rust` plugin when specified during packing, under the impression that it was a local plugin.

### To Reproduce

1. Add `rust` into Snapcraft's virtual environment
1. Build any snap with the Rust plugin

### Environment

24.10, Snapcraft 8.5.1

### snapcraft.yaml

```yaml
name: rust-hello
version: "1.0"
summary: simple rust application
description: build a rust app using core20
base: core20
confinement: strict

apps:
  rust-hello:
    command: target/hello

parts:
  hello:
    plugin: rust
    source: src
```

### Relevant log output

```shell
https://github.com/canonical/snapcraft/actions/runs/12682069561/job/35347202604?pr=5196#step:4:1051
```
