### ISSUE TITLE
Support foreign architectures

### ISSUE THREAD

**Issue by mr-cal** [canonical/snapcraft#5222]
### What needs to get done

* Update craft-archives to bring https://github.com/canonical/craft-archives/issues/104
* Add a variant to `tests/spread/general/stage-packages` that exercises the following:

```yaml
name: curl-consumer
version: "0.1"
summary: cross-compiled curl consumer
description: |
  A cross-compiled snap that uses libcurl. This exercises installing
  libcurl-dev as a build package and staging libcurl, both from the armhf
  repo.
grade: devel
base: core24
confinement: strict

platforms:
  armhf:
    build-on: [amd64]
    build-for: [armhf]

lint:
  ignore:
    - library

apps:
  curl-consumer:
    command: usr/bin/curl-consumer

package-repositories:
  - type: apt
    architectures: [armhf]
    components: [main]
    suites: [noble]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    url: http://ports.ubuntu.com/ubuntu-ports

parts:
  curl-consumer:
    plugin: autotools
    source: src
    build-environment:
      - PKG_CONFIG_PATH: "/usr/lib/arm-linux-gnueabihf/pkgconfig"
    build-packages:
      - libcurl4-openssl-dev:armhf
    stage-packages:
      - libcurl4t64:armhf
    autotools-configure-parameters:
      - --prefix=/usr
      - --host=${CRAFT_ARCH_TRIPLET_BUILD_FOR}
```

### Why it needs to get done

To improve the UX for cross-compiled `core24` snaps.
