### ISSUE TITLE
Flutter plugin breaks during precache

### ISSUE THREAD

**Issue by bepri** [canonical/snapcraft#5258]
### Bug Description

Currently, the Flutter plugin installs Flutter using an undocumented git-based method, which breaks due to what appear to be some internal forks to `git` in Flutter:
```
 :: + flutter precache --linux
::    Woah! You appear to be trying to run flutter as root.
::    We strongly recommend running the flutter tool without superuser privileges.
::   /
:: 📎
:: fatal: Not a valid object name origin/master
```
(note the last line especially)

The issue here is that we clone with `-b stable`, which means only the `stable` branch is present locally. Cloning the `master` branch instead gets us further, but still fails due to what appears to be the Flutter repository using a placeholder "0.0.0" version in that branch.

However, there _is_ a Flutter snap, which does not appear to have any of these troubles.

We could, alternatively, rename the local remote `stable` to `master` as a workaround.

### To Reproduce

Attempt to build anything with the Flutter plugin

### Environment

Any version of Snapcraft

### snapcraft.yaml

```yaml
name: flutter-hello
version: "1.0"
summary: simple flutter application
description: build a flutter application using core22
base: core22
confinement: strict

apps:
  flutter-hello:
    command: "flutter_hello"
    extensions: [gnome]

parts:
  hello:
    source: .
    plugin: flutter
```

### Relevant log output

```shell
:: + flutter precache --linux
::    Woah! You appear to be trying to run flutter as root.
::    We strongly recommend running the flutter tool without superuser privileges.
::   /
:: 📎
:: fatal: Not a valid object name origin/master
```
