### ISSUE TITLE
Metainfo (Appstream) data is not used (adopt-info, parse-info)

### ISSUE THREAD

**Issue by knipknap** [canonical/snapcraft#5278]
### Bug Description

Given the following snapcraft.yaml:

```
name: rayforge
version: git
adopt-info: rayforge
confinement: strict
base: core24

apps:
  rayforge:
    extensions: [gnome]
    common-id: com.barebaric.rayforge
    desktop: share/applications/com.barebaric.rayforge.desktop

...

parts:
  rayforge:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    build-packages:
      - python3-pip
      - python3-setuptools
      - git  # Required for git describe
    parse-info: [share/metainfo/com.barebaric.rayforge.metainfo.xml]
```
Full file: https://github.com/barebaric/rayforge/blob/main/snap/snapcraft.yaml

I am seeing that **some** attributes from the metadata appear to be adopted, while others are not.

**What works**: Summary and description.

**What doesn't work**: Website, license, screenshots, categories, ...

I am puzzled. Running snapcraft with `--verbosity debug` does not reveal anything containing "appstream" or "metainfo".

Here is the full metainfo:

```
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
  <id>com.barebaric.rayforge</id>
  <developer id="com.barebaric">
    <name translate="no">Samuel Abels</name>
  </developer>
  <content_rating type="oars-1.1" />
  <url type="homepage">https://github.com/barebaric/rayforge</url>
  <url type="bugtracker">https://github.com/barebaric/rayforge/issues</url>

  <name>Rayforge</name>
  <summary>A desktop application for laser cutting and engraving</summary>

  <categories>
    <category>Utility</category>
    <category>Engineering</category>
  </categories>

  <metadata_license>MIT</metadata_license>
  <project_license>MIT</project_license>

  <description>
    <p>
      Rayforge is a desktop application for laser cutting and engraving.
      It provides an intuitive interface to create and manage laser
      cutting projects.
      Rayforge supports importing SVG, DXF, PDF, and PNGs, and provides
      advanced features such as multi step jobs, automatic path
      optimization, interpolation based on laser dot size, and much more.
    </p>
  </description>
  
  <launchable type="desktop-id">com.barebaric.rayforge.desktop</launchable>

  <recommends>
    <control>keyboard</control>
    <control>pointing</control>
    <display_length compare="ge">768</display_length>
  </recommends>

  <icon type="local">share/icons/hicolor/scalable/apps/com.barebaric.rayforge.svg</icon>

  <branding>
    <color type="primary" scheme_preference="light">#efb0a1</color>
    <color type="primary" scheme_preference="dark">#373f43</color>
  </branding>

  <screenshots>
    <screenshot type="default">
      <caption>The main window of Rayforge.</caption>
      <image type="source" width="1462" height="1209">https://raw.githubusercontent.com/barebaric/rayforge/main/docs/ss-main.png</image>
    </screenshot>
  </screenshots>

  <releases>
    <release version="0.1" date="2025-02-08">
      <description>
        <p>This is the initial release.</p>
      </description>
    </release>
  </releases>
</component>
```

### To Reproduce

```
git clone git@github.com:barebaric/rayforge.git
cd rayforge
snapcraft --verbosity debug
```

Note that it builds successfully, but after `snapcraft upload` the info is incomplete.

![Image](https://github.com/user-attachments/assets/98e020fd-a669-41c5-bb78-d4b0d47c4f4e)

### Environment

Ubuntu, or Github pipeline, too. Example build: 
https://github.com/barebaric/rayforge/actions/runs/13482604479/job/37669702127

### Relevant log output

```shell
No relevant logs as far as I can see. Example build see here:
https://github.com/barebaric/rayforge/actions/runs/13482604479/job/37669702127
```

**Comment by mr-cal** [comment]
Hi, if you inspect the snap, is the missing metadata present in `meta/snap.yaml`?

**Comment by knipknap** [comment]
It seems not:


```
name: rayforge
title: Rayforge
version: 0.10+git2.af17176
summary: A desktop application for laser cutting and engraving
description: |-
  Rayforge is a desktop application for laser cutting and engraving.
  It provides an intuitive interface to create and manage laser
  cutting projects.
  Rayforge support communicating with GRBL based laser cutters.
  Rayforge supports importing SVG, DXF, PDF, and PNGs, and provides
  advanced features such as multi step jobs, automatic path
  optimization, interpolation based on laser dot size, and much more.
license: MIT
architectures:
- amd64
base: core24
assumes:
- command-chain
- snapd2.43
apps:
  rayforge:
    command: bin/rayforge
    common-id: com.barebaric.rayforge
    plugs:
    - desktop
    - desktop-legacy
    - gsettings
    - opengl
    - wayland
    - x11
    - home
    - network
    - network-bind
    - removable-media
    environment:
      GI_TYPELIB_PATH: $SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.10/site-packages
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/blas:$SNAP/usr/lib/x86_64-linux-gnu/lapack:$SNAP/usr/lib/$ARCH/libproxy
    command-chain:
    - snap/command-chain/gpu-2404-wrapper
    - snap/command-chain/desktop-launch
confinement: strict
grade: stable
environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
  GTK_USE_PORTAL: '1'
  LD_LIBRARY_PATH: ${SNAP_LIBRARY_PATH}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}:$SNAP/lib
  PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
plugs:
  desktop:
    mount-host-font-cache: false
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  gnome-46-2404:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-46-2404
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404
slots:
  rayforge:
    interface: dbus
    bus: session
    name: com.barebaric.rayforge
hooks:
  configure:
    command-chain:
    - snap/command-chain/hooks-configure-fonts
    plugs:
    - desktop
layout:
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0:
    bind: $SNAP/gnome-platform/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1
  /usr/share/xml/iso-codes:
    bind: $SNAP/gnome-platform/usr/share/xml/iso-codes
  /usr/share/libdrm:
    bind: $SNAP/gpu-2404/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/gpu-2404/drirc.d
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/gpu-2404/X11/XErrorDB
links:
  issues:
  - https://github.com/barebaric/rayforge/issues
  website:
  - https://github.com/barebaric/rayforge

```

**Comment by mr-cal** [comment]
I see some links are getting parsed and added to the metadata:
```yaml
summary: A desktop application for laser cutting and engraving
description: |-
  Rayforge is a desktop application for laser cutting and engraving.

...

license: MIT

...

links:
  issues:
  - https://github.com/barebaric/rayforge/issues
  website:
  - https://github.com/barebaric/rayforge
```

I believe the store is supposed to add those to the store listing automatically, but I'm not sure where that's documented.  I'd recommend making a [forum post](https://forum.snapcraft.io/) in the store category or an [issue](https://launchpad.net/snapstore-server) in the Snap store launchpad repo.

It would be nice if Snapcraft pulled screenshots out of the metadata but it would require the Snap store to consume those screenshots programmatically.  A request for this in the forum or Snap store would be a good place to start.

Since snapcraft is parsing and adding this information to the metadata file and this needs follow up with the Snap store, I'm going to close this issue in the Snapcraft repo.
