### ISSUE TITLE
Failed to build a snap package using the Crystal plugin

### ISSUE THREAD

**Issue by mamantoha** [canonical/snapcraft#5330]
### Bug Description

This issue started happening recently for all my Snap builds using the Crystal plugin.

I haven’t made any changes to my  `snapcraft.yml`. 
After reviewing the codebase, I believe this is related to this commit by @bepri – https://github.com/canonical/snapcraft/commit/54b12c1880130d371d6f4cd29a8f0ee12ed2de95.

Here is the diff output comparing a successful build and a failed one:

![Image](https://github.com/user-attachments/assets/05ce8854-4d51-4696-8fc0-615a87d602a1)

### To Reproduce

Build a snap with Crystal plugin

### Environment

https://snapcraft.io

### snapcraft.yaml

```yaml
name: speedtest-ng
base: core20
version: '0.5.2'
summary: A command-line tool for testing internet speed using Speedtest.net
description: |
  A command-line tool for testing internet speed using Speedtest.net, written in Crystal.
  Inspired by the Python-based speedtest-cli.
contact: anton.maminov@gmai.com

grade: stable
confinement: strict

type: app
architectures: [amd64]
compression: lzo

license: MIT

website: https://github.com/mamantoha/speedtest-ng
issues: https://github.com/mamantoha/speedtest-ng/issues
source-code: https://github.com/mamantoha/speedtest-ng.git

apps:
  speedtest-ng:
    command: bin/speedtest-ng
    plugs:
      - network

parts:
  speedtest-ng:
    plugin: crystal
    source: ./
    crystal-build-options:
    - -Dpreview_mt
```

### Relevant log output

```shell
Pulling speedtest-ng 
+ snapcraftctl pull
Running build phase...
'libz-dev' is a virtual package, use non virtual packages for deterministic results.
Skipping pull speedtest-ng (already ran)
Building speedtest-ng 
+ snapcraftctl build
+ shards build --without-development -Dpreview_mt
I: Resolving dependencies
I: Fetching https://github.com/geocrystal/haversine.git
[12/Mar/2025:13:06:12 +0000] "CONNECT github.com:443 HTTP/1.1" 200 937232 "-" "git/2.25.1"
I: Installing haversine (0.5.0)
I: Building: speedtest-ng
+ cp -r ./bin /build/speedtest-ng/parts/speedtest-ng/install/bin
+ env -i LANG=C.UTF-8 LC_ALL=C.UTF-8 SNAP=/snap/snapcraft/13860 SNAPCRAFT_BUILD_ENVIRONMENT=host SNAPCRAFT_BUILD_FOR=amd64 SNAPCRAFT_BUILD_INFO=True 'SNAPCRAFT_IMAGE_INFO={build-request-id:' lp-96736513, build-request-timestamp: 2025-03-12T13:03:17Z, build_url: 'https://launchpad.net/~build.snapcraft.io/+snap/b7b42d06e84aee9b99fde0fc3ab51a24/+build/2750080}' SNAPPY_STORE_NO_CDN=1 SNAP_ARCH=amd64 SNAP_COMMON=/var/snap/snapcraft/common SNAP_CONTEXT=VZD5sgFhNd1A8TZHofR3bxpkylqWfVtYWod20Dvf-OmwML9Ut8NG SNAP_COOKIE=VZD5sgFhNd1A8TZHofR3bxpkylqWfVtYWod20Dvf-OmwML9Ut8NG SNAP_DATA=/var/snap/snapcraft/13860 SNAP_EUID=0 SNAP_INSTANCE_KEY= SNAP_INSTANCE_NAME=snapcraft SNAP_LIBRARY_PATH=/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void SNAP_NAME=snapcraft SNAP_REAL_HOME=/root SNAP_REEXEC= SNAP_REVISION=13860 SNAP_UID=0 SNAP_USER_COMMON=/root/snap/snapcraft/common SNAP_USER_DATA=/root/snap/snapcraft/13860 SNAP_VERSION=8.7.2 /snap/snapcraft/13860/bin/python -I /snap/snapcraft/13860/lib/python3.12/site-packages/snapcraft_legacy/plugins/v2/crystal.py stage-runtime-dependencies --part-src /build/speedtest-ng/parts/speedtest-ng/src --part-install /build/speedtest-ng/parts/speedtest-ng/install --part-build /build/speedtest-ng/parts/speedtest-ng/build --arch-triplet x86_64-linux-gnu --content-dirs ''
env: ‘lp-96736513,’: No such file or directory
Failed to build 'speedtest-ng'.
```
