### ISSUE TITLE
Keep running into `resource-not-found`

### ISSUE THREAD

**Issue by rikhuijzer** [canonical/snapcraft#5382]
### Bug Description

Thank you all for working on the snap store. I'm trying to publish a new snap, but even though I have followed the instructions in the manual, I keep seeing:

```sh
$ snapcraft upload --release=stable jas_0.2.0_amd64.snap
Store operation failed:
- resource-not-found: Snap not found for name=jas
```

This is while I did follow the instructions in the manual. 

### To Reproduce

I have successfully registered this name with:

```sh
$ snapcraft register jas
``` 
which succeeded and I can also see it at <https://snapcraft.io/snaps>

Then I tried to publish, with `snapcraft upload` but keep getting the same error. My attempts are visible at https://github.com/rikhuijzer/jas/pull/18. I'm running in a CI job because I couldn't get the build to succeed via multipass locally on MacOS and also not inside a Hetzner Ubuntu VM.

### Environment

See https://github.com/rikhuijzer/jas/pull/18

### snapcraft.yaml

```yaml
name: jas
version: '0.2.0'
summary: Just an installer
description: |
   This tool is meant to be used in situations where you want to install a
   binary in a reliable way, that is, by specifying the SHA-256 checksum. The
   checksum ensures that the binary is exactly the one you expect it to be.
confinement: strict
base: core22
# grade: devel
license: MIT

parts:
  jas:
    build-packages:
      - pkg-config
      - cargo
    plugin: rust
    source: .
# I have also tried `grade: devel` with `--release edge`.
apps:
  jas:
    command: bin/jas
    plugs:
      - network
      - home
```

### Relevant log output

```shell
Store operation failed:
- resource-not-found: Snap not found for name=jas
```
