### ISSUE TITLE
Use the platform in snap names to prevent overwrites

### ISSUE THREAD

**Issue by mr-cal** [canonical/snapcraft#5399]
### What needs to get done

Snapcraft should use the platform name in the snap filename rather than the build-for arch. ([source](https://github.com/canonical/snapcraft/blob/5e21a93fc2ab8bea9e49b0cf941c10adff0f5bf1/snapcraft/pack.py#L65))

### Why it needs to get done

Using the platforms entry:
```yaml
name: hello
base: core24
version: '0.1'
summary: hello
description: hello
grade: devel
confinement: devmode

platforms:
  release:
    build-on: [amd64]
    build-for: [amd64]
  debug:
    build-on: [amd64]
    build-for: [amd64]


parts:
  my-part:
    plugin: nil
```
and building on amd64 will create 2 snaps, both named `hello_0.1_amd64.snap`.  The second snap file will silently overwrite the first.
