### ISSUE TITLE
`${SNAPCRAFT_PROJECT_VERSION}` no longer works in URLs

### ISSUE THREAD

**Issue by Mailaender** [canonical/snapcraft#5491]
### Bug Description

https://github.com/OpenChrom/openchrom-snap/actions/runs/15069778758/job/42362912240

### To Reproduce

https://github.com/OpenChrom/openchrom-snap/tree/8789bf7804dda4d944f760a4af12de611d2929ef

### Environment

Use https://github.com/snapcore/action-build

### snapcraft.yaml

```yaml
name: openchrom
base: core24
version: 1.5.10
summary: Visualization and Analysis of mass spectrometric and chromatographic data.
description: OpenChrom® is an Open Source tool for the analysis and visualization of mass spectrometric and chromatographic data developed by Lablicate GmbH.
grade: stable
confinement: strict
platforms:
  amd64: null
  arm64: null
apps:
  openchrom:
    extensions:
    - gnome
    command: bin/openchrom-wrapper
    plugs:
    - browser-support
    - home
    - password-manager-service
    - mount-observe
    - network
    - network-bind
    - removable-media
    - x11
    - dot-eclipse-org-eclipse-swtchart-extensions
    - dot-openchrom
parts:
  openchrom:
    plugin: dump
    source:
    - on amd64: https://products.lablicate.com/openchrom/${SNAPCRAFT_PROJECT_VERSION}/openchrom-lablicate_linux.x86_64_${SNAPCRAFT_PROJECT_VERSION}.tar.gz
    - on arm64: https://products.lablicate.com/openchrom/${SNAPCRAFT_PROJECT_VERSION}/openchrom-lablicate_linux.aarch64_${SNAPCRAFT_PROJECT_VERSION}.tar.gz
    override-build: |
      craftctl default
      sed -i 's;@user.home/;@user.home/snap/openchrom/current/;' $SNAPCRAFT_PART_INSTALL/openchrom.ini
    stage-packages:
    - libgtk-3-0
    - libusb-1.0-0
    - libwebkit2gtk-4.1-0
    - libsecret-1-0
    - librsvg2-common
    override-prime: |
      craftctl default
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/aix*/
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/darwin*/
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/dragonflybsd*/
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/freebsd*/
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/openbsd*/
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/sunos*/
      rm -r $SNAPCRAFT_PRIME/plugins/com.sun.jna_*v*/com/sun/jna/win32*/
  wrappers:
    plugin: dump
    source: snap/local/wrappers
    organize:
      openchrom: bin/openchrom-wrapper
plugs:
  dot-eclipse-org-eclipse-swtchart-extensions:
    interface: personal-files
    write:
    - $HOME/.eclipse/org.eclipse.swtchart.extensions
  dot-openchrom:
    interface: personal-files
    write:
    - $HOME/.openchrom
lint:
  ignore:
  - library:
    - plugins/**/*.so
    - features/*/jre/*/lib/*.so
    - usr/lib/**/*.so*
```

### Relevant log output

```shell
Cannot process request (Forbidden: 403): https://products.lablicate.com/openchrom/${SNAPCRAFT_PROJECT_VERSION}/openchrom-lablicate_linux.x86_64_${SNAPCRAFT_PROJECT_VERSION}.tar.gz
```

### Additional context

If this is on purpose then you need to update https://snapcraft.io/docs/parts-environment-variables
