### ISSUE TITLE
Handle project variables in app commands

### ISSUE THREAD

**Issue by mr-cal** [canonical/snapcraft#5500]
### What needs to get done

Snapcraft should not fail when project variables are used in app commands.

### Why it needs to get done

This is a regression.  Prior to https://github.com/canonical/snapcraft/pull/5183, Snapcraft used to allow:

```yaml
apps:
  my-app:
    command: bin/${SNAPCRAFT_PROJECT_NAME}
```
