### ISSUE TITLE
Name snap files after the platform

### ISSUE THREAD

**Issue by cmatsuoka** [canonical/snapcraft#5538]
### Bug Description

If building for multiple platforms using the same architecture, generated artifacts are overwritten by the next platform.

### To Reproduce

Create a new project with `snapcraft init`. Edit the project file and declare two platforms with the same build-on/build-for entries, and run `snapcraft pack --verbose`.

### Environment

Snapcraft 8.8.1 running in managed mode.

### snapcraft.yaml

```yaml
platforms:
  plat1:
    build-on: amd64
    build-for: amd64
  plat2:
    build-on: amd64
    build-for: amd64
```

### Relevant log output

```shell
Launching managed ubuntu 24.04 instance...
Creating instance from base instance
Starting instance
...
Creating snap package...
Packed xx-test_0.1_amd64.snap
Launching managed ubuntu 24.04 instance...
Creating instance from base instance 
Starting instance
...
Creating snap package...
Packed xx-test_0.1_amd64.snap
```
